-- Module Agenda : voyages du foyer + paramètres du foyer (zone scolaire). Additif, idempotent.
--
-- Pourquoi : MaxVoyage garde ses carnets de voyage en HTML écrits à la main, avec des
-- données personnelles (dates, budget, âge de l'enfant) — ils ne peuvent pas entrer dans ce
-- dépôt public (invariant 1). Ici ne vit que le strict nécessaire pour les poser sur un
-- calendrier : un titre, un lieu, deux dates, une note. Les vacances scolaires ne sont PAS
-- stockées : l'app les lit sur data.education.gouv.fr (frontend/agenda/vacances.js) et ne
-- garde en base que la zone du foyer.

create table if not exists voyages (
  id        bigint generated by default as identity primary key,
  titre     text not null,
  lieu      text,
  debut     date not null,
  fin       date not null,
  note      text,
  cree_par  text,
  cree_le   timestamptz not null default now(),
  constraint voyages_fin_apres_debut check (fin >= debut)
);
create index if not exists voyages_debut on voyages (debut);

-- Paramètres du foyer, clé/valeur texte. Une seule ligne par clé ; « zone » vaut par exemple
-- « Zone C ». Aucune valeur seedée ici : l'app applique son défaut tant que la clé manque.
create table if not exists parametres (
  cle    text primary key,
  valeur text not null
);

alter table voyages    enable row level security;
alter table parametres enable row level security;
drop policy if exists voyages_rw    on voyages;
drop policy if exists parametres_rw on parametres;
create policy voyages_rw    on voyages    for all using (est_membre()) with check (est_membre());
create policy parametres_rw on parametres for all using (est_membre()) with check (est_membre());

select (select count(*) from voyages) as voyages, (select count(*) from parametres) as parametres;
