-- Module Agenda : le carnet de voyage (D-045). Additif, idempotent.
--
-- Pourquoi : un carnet HTML (MaxVoyage) mélange trois choses qui vivent différemment — la
-- prose (topo), les lieux (carte, jour par jour, bot) et les réservations (données strictes :
-- code, prix, payeur). On les sépare en trois tables typées + un champ texte sur `voyages`,
-- pour que la carte, le budget et « la prochaine résa » se lisent sans reparser du HTML.
-- Les billets/QR/PDF sont des fichiers : `voyage_pieces` + bucket Storage privé `voyages`,
-- jamais d'URL publique (lecture par URL signée courte, côté app).
-- Remplace l'arbitrage de D-037 (« les carnets restent dans MaxVoyage ») : ils entrent en
-- base, derrière la connexion, jamais dans git (invariant 1).

alter table voyages add column if not exists topo    text;
alter table voyages add column if not exists topo_le timestamptz;

create table if not exists voyage_lieux (
  id         bigint generated by default as identity primary key,
  voyage_id  bigint not null references voyages(id) on delete cascade,
  nom        text not null,
  categorie  text not null default 'a_voir'
             check (categorie in ('a_voir', 'activite', 'logement', 'resto', 'transport', 'autre')),
  statut     text not null default 'idee'
             check (statut in ('idee', 'prevu', 'fait', 'ecarte')),
  jour       date,
  ordre      int not null default 0,
  lat        double precision,
  lng        double precision,
  adresse    text,
  note       text,
  lien       text,
  cree_par   text,
  cree_le    timestamptz not null default now(),
  constraint voyage_lieux_position_complete check ((lat is null) = (lng is null)),
  constraint voyage_lieux_lat_bornee check (lat is null or lat between -90 and 90),
  constraint voyage_lieux_lng_bornee check (lng is null or lng between -180 and 180)
);
create index if not exists voyage_lieux_voyage on voyage_lieux (voyage_id);

create table if not exists voyage_resas (
  id             bigint generated by default as identity primary key,
  voyage_id      bigint not null references voyages(id) on delete cascade,
  type           text not null default 'autre'
                 check (type in ('vol', 'train', 'logement', 'voiture', 'activite', 'autre')),
  titre          text not null,
  debut          timestamp,
  fin            timestamp,
  prestataire    text,
  code           text,
  prix_centimes  integer check (prix_centimes >= 0),
  paye_par       text,
  statut         text not null default 'reserve'
                 check (statut in ('a_reserver', 'reserve', 'annule')),
  lieu_id        bigint references voyage_lieux(id) on delete set null,
  note           text,
  cree_par       text,
  cree_le        timestamptz not null default now()
);
create index if not exists voyage_resas_voyage on voyage_resas (voyage_id);

create table if not exists voyage_pieces (
  id         bigint generated by default as identity primary key,
  voyage_id  bigint not null references voyages(id) on delete cascade,
  resa_id    bigint references voyage_resas(id) on delete cascade,
  nom        text not null,
  chemin     text not null unique,
  type_mime  text,
  taille     integer,
  cree_par   text,
  cree_le    timestamptz not null default now()
);
create index if not exists voyage_pieces_voyage on voyage_pieces (voyage_id);

alter table voyage_lieux  enable row level security;
alter table voyage_resas  enable row level security;
alter table voyage_pieces enable row level security;
drop policy if exists voyage_lieux_rw  on voyage_lieux;
drop policy if exists voyage_resas_rw  on voyage_resas;
drop policy if exists voyage_pieces_rw on voyage_pieces;
create policy voyage_lieux_rw  on voyage_lieux  for all using (est_membre()) with check (est_membre());
create policy voyage_resas_rw  on voyage_resas  for all using (est_membre()) with check (est_membre());
create policy voyage_pieces_rw on voyage_pieces for all using (est_membre()) with check (est_membre());

-- Bucket privé pour les billets/QR/PDF. `public = false` : toute lecture passe par une URL
-- signée courte, jamais par une URL publique. Chemin d'un fichier : <voyage_id>/<uuid>.<ext>.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('voyages', 'voyages', false, 10485760,
        array['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'application/pdf'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists voyages_stockage_select on storage.objects;
drop policy if exists voyages_stockage_insert on storage.objects;
drop policy if exists voyages_stockage_update on storage.objects;
drop policy if exists voyages_stockage_delete on storage.objects;
create policy voyages_stockage_select on storage.objects for select
  using (bucket_id = 'voyages' and public.est_membre());
create policy voyages_stockage_insert on storage.objects for insert
  with check (bucket_id = 'voyages' and public.est_membre());
create policy voyages_stockage_update on storage.objects for update
  using (bucket_id = 'voyages' and public.est_membre())
  with check (bucket_id = 'voyages' and public.est_membre());
create policy voyages_stockage_delete on storage.objects for delete
  using (bucket_id = 'voyages' and public.est_membre());

select (select count(*) from voyage_lieux) as lieux, (select count(*) from voyage_resas) as resas,
       (select count(*) from voyage_pieces) as pieces,
       (select count(*) from storage.buckets where id = 'voyages') as bucket;
