-- Carnet de voyage V2 (D-047) : le récit en blocs typés, le budget en enveloppes par poste.
-- Additif, idempotent.
--
-- Pourquoi : Yann veut éditer le topo « en bloc » (un bloc par idée, coloré, réordonnable) et
-- cadrer le budget par poste avant de cocher les dépenses au fil de l'eau. `voyages.topo` reste
-- en base (jamais supprimé, plus lu par l'écran V2) : `scripts/topo_en_blocs.py` le découpe une
-- fois en `voyage_blocs`. Une résa EST une ligne de dépense (poste ajouté) : pas de table
-- « dépenses » qui doublerait voyage_resas.

create table if not exists voyage_blocs (
  id         bigint generated by default as identity primary key,
  voyage_id  bigint not null references voyages(id) on delete cascade,
  type       text not null default 'info'
             check (type in ('resume', 'info', 'astuce', 'attention')),
  titre      text,
  texte      text not null default '',
  ordre      int not null default 0,
  cree_par   text,
  cree_le    timestamptz not null default now(),
  maj_le     timestamptz not null default now()
);
create index if not exists voyage_blocs_voyage on voyage_blocs (voyage_id);
-- Au plus un bloc `resume` par voyage : index unique partiel.
create unique index if not exists voyage_blocs_un_resume_par_voyage
  on voyage_blocs (voyage_id) where (type = 'resume');

create table if not exists voyage_enveloppes (
  id             bigint generated by default as identity primary key,
  voyage_id      bigint not null references voyages(id) on delete cascade,
  poste          text not null
                 check (poste in ('transport', 'logement', 'activites', 'repas', 'sur_place', 'autre')),
  prevu_centimes integer not null check (prevu_centimes >= 0),
  note           text,
  unique (voyage_id, poste)
);
create index if not exists voyage_enveloppes_voyage on voyage_enveloppes (voyage_id);

alter table voyage_resas add column if not exists poste text;

-- Contrainte `type` élargie à `repas` : drop puis recrée (idempotent, Postgres n'a pas de
-- `add constraint if not exists` pour un check nommé implicitement ici on le nomme).
alter table voyage_resas drop constraint if exists voyage_resas_type_check;
alter table voyage_resas add constraint voyage_resas_type_check
  check (type in ('vol', 'train', 'logement', 'voiture', 'activite', 'autre', 'repas'));

alter table voyage_resas drop constraint if exists voyage_resas_poste_check;
alter table voyage_resas add constraint voyage_resas_poste_check
  check (poste is null or poste in ('transport', 'logement', 'activites', 'repas', 'sur_place', 'autre'));

-- Postes des résas existantes, déduits du type (frontend/agenda/carnet.js::posteDe, même règle) :
-- vol/train/voiture -> transport, logement -> logement, activite -> activites, repas -> repas,
-- autre -> autre. Ne touche pas une résa dont le poste est déjà renseigné (ré-exécution sûre).
update voyage_resas set poste = case type
  when 'vol' then 'transport'
  when 'train' then 'transport'
  when 'voiture' then 'transport'
  when 'logement' then 'logement'
  when 'activite' then 'activites'
  when 'repas' then 'repas'
  else 'autre'
end
where poste is null;

alter table voyage_blocs      enable row level security;
alter table voyage_enveloppes enable row level security;
drop policy if exists voyage_blocs_rw      on voyage_blocs;
drop policy if exists voyage_enveloppes_rw on voyage_enveloppes;
create policy voyage_blocs_rw      on voyage_blocs      for all using (est_membre()) with check (est_membre());
create policy voyage_enveloppes_rw on voyage_enveloppes for all using (est_membre()) with check (est_membre());

select (select count(*) from voyage_blocs) as blocs, (select count(*) from voyage_enveloppes) as enveloppes,
       (select count(*) from voyage_resas where poste is null) as resas_sans_poste;
