-- Alertes de veille vols (docs/briefs/veille-vols.md, D-056) : ce que MaxVoyage doit surveiller,
-- saisi depuis l'app. MaxHome fait foi ; MaxVoyage recopie ces lignes dans sa base locale au
-- début de chaque collecte (scripts/lire_alertes.py). Une alerte supprimée ici est désactivée
-- là-bas (son historique de prix reste). Additif, idempotent.
-- `id` accepte une valeur fournie : les alertes existantes de MaxVoyage gardent leur numéro.
create table if not exists veille_alertes (
  id                    bigint generated by default as identity primary key,
  nom                   text not null check (length(nom) between 1 and 100),
  type                  text not null default 'vacances' check (type in ('vacances', 'weekend')),
  periode_libelle       text not null check (length(periode_libelle) between 1 and 100),
  debut                 date not null,
  fin                   date not null,
  zone                  text not null default 'Zone C',
  marge_avant           int  not null default 2 check (marge_avant between 0 and 14),
  marge_apres           int  not null default 2 check (marge_apres between 0 and 14),
  nuits_min             int  not null check (nuits_min between 1 and 60),
  nuits_max             int  not null check (nuits_max between 1 and 60),
  jours_depart          int[] null,                         -- 0 = lundi … 6 = dimanche ; null = tous
  origines              text[] not null default '{ORY}',
  destinations          text[] not null,
  prix_max_pp_centimes  int  null check (prix_max_pp_centimes is null or prix_max_pp_centimes >= 0),
  directs_seulement     boolean not null default false,
  recherches_max        int  not null default 8 check (recherches_max between 1 and 120),
  adultes               int  not null default 2 check (adultes between 0 and 9),
  enfants_naissances    date[] not null default '{}',
  active                boolean not null default true,
  maj_le                timestamptz not null default now(),
  check (fin >= debut),
  check (nuits_max >= nuits_min),
  check (cardinality(destinations) between 1 and 40),
  check (cardinality(origines) between 1 and 2)
);

alter table veille_alertes enable row level security;
do $$
begin
  if not exists (select 1 from pg_policies where tablename = 'veille_alertes' and policyname = 'veille_alertes_rw') then
    create policy veille_alertes_rw on veille_alertes for all using (est_membre()) with check (est_membre());
  end if;
end $$;
